name: Version bump on development

on:
  push:
    branches:
      - development

jobs:
  version-bump:
    name: Bump app version
    runs-on: ubuntu-latest
    steps:
      - name: Trigger react-native-version action
        uses: nabeel-shakeel/react-native-version@main
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: 'v'
          commit-message: 'chore: react native - android & ios versions updated'
          automatic_release_tag: 'latest'

